### ISSUE TITLE
Y Carrier Fork_2x_SN_BO protrusions prevent insertion into Y Carrier_2x_SB_BN

### ISSUE THREAD

**Issue by karllane** [RoyBerntsenDesign/V-Baby-CoreXY#2]
There are protrusions at the end of the Y Carrier Fork that prevent it from being inserted into the Y Carrier.

**Comment by RoyBerntsenDesign** [comment]
Oh right.. Thanks for mentioning. Let me fix that tonight

man. 4. mai 2020, 20:04 skrev karllane <notifications@github.com>:

**Comment by RoyBerntsenDesign** [comment]
Resolved?
